### ISSUE TITLE
Other data sources

### ISSUE THREAD

**Issue by mgifford** [accessiblecommunity/useable#10]
We pulled together a similar list. 

https://github.com/CivicActions/accessibility-data-reference

Can be useful to have data in CSV & JSON formats, as so many folks use spreadsheets.

**Comment by brian-montgomery** [comment]
On our [github page](https://accessiblecommunity.github.io/useable/), we provide a download as JSON. We'd be happy to take the original CSVs and zip them up as part of the site.
